---

- name: set vm
  sysctl: name=vm.swappiness value=0 state=present reload=yes

- name: set net core somaxconn
  sysctl: name=net.core.somaxconn value=65536 state=present reload=yes

- name: set tcp max tw buckets
  sysctl: name=net.ipv4.tcp_max_tw_buckets value=5000 state=present reload=yes

- name: set tcp max syn backlog
  sysctl: name=net.ipv4.tcp_max_syn_backlog value=1024 state=present reload=yes

- name: Harden TCP/IP stack against SYN floods
  sysctl: name="net.ipv4.tcp_syncookies" value=1 sysctl_set=yes state=present reload=yes
