# Generated by Django 2.2.9 on 2020-02-01 06:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExChangeRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, editable=False, unique=True
                    ),
                ),
                ("rates", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        )
    ]
