# Generated by Django 2.2.10 on 2020-02-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("exchangerates", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="exchangerate", options={"ordering": ["-date"]}
        )
    ]
