# Generated by Django 2.2.11 on 2020-03-13 07:54

import apps.images.handlers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200224_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=apps.images.handlers.UUIDFilename('images/')),
        ),
    ]
