# configure updates globally
# default: all
# allowed: all, insecure, False
update: insecure

# set the default branch
# default: empty, the default branch on GitHub
branch: master


requirements:
  - requirements/local.txt:
      update: all
  - requirements/production.txt:
      update: insecure