# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 13:14
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models
import editormd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(default='', editable=False, max_length=30, unique=True)),
                ('content', editormd.models.EditorMdField()),
                ('status', models.IntegerField(choices=[(0, 'block'), (1, 'preview'), (2, 'publish')], default=1, verbose_name='status')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_date')),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='last_update')),
            ],
            options={
                'ordering': ['-created_date'],
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
