# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 03:37
from __future__ import unicode_literals

from django.db import migrations
import editormd.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=editormd.models.EditorMdField(),
        ),
    ]
