# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0002_auto_20190604_1721")]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "posts",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.RenameField(
            model_name="post", old_name="created_date", new_name="created_at"
        ),
    ]
