# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180530_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
