---
# tasks file for django

- include_tasks: install_additional_packages.yml
  tags: packages

- include_tasks: setup_virtualenv.yml
  tags: virtualenv

- include_tasks: setup_git_repo.yml
  tags: deploy

- include_tasks: setup_django_app.yml
  tags: deploy

- include_tasks: setup_supervisor.yml
  tags: supervisor


- include_tasks: setup_cron.yml
  tags: deploy


- name: Create the Nginx configuration file
  template: src={{ application_name }}_nginx.j2
            dest=/etc/nginx/sites-available/{{ application_name }}
            backup=yes
  notify: reload nginx


- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ application_name }}
        dest=/etc/nginx/sites-enabled/{{ application_name }}
        state=link
  notify: reload nginx
