# Generated by Django 3.2.9 on 2021-11-30 15:55

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cryptonews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=django_extensions.db.fields.RandomCharField(
                blank=True,
                db_index=True,
                editable=False,
                include_alpha=False,
                length=12,
                unique=True,
            ),
        ),
    ]
