# Generated by Django 3.2.9 on 2021-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptonews", "0002_news_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-published_at"]},
        ),
        migrations.AlterField(
            model_name="news",
            name="origin_link",
            field=models.URLField(
                blank=True, max_length=1024, null=True, unique=True
            ),
        ),
    ]
