# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, db_index=True, editable=False, include_alpha=False, length=12, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated_at')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('press', models.CharField(blank=True, max_length=128)),
                ('version', models.CharField(max_length=30)),
                ('license', models.CharField(max_length=64)),
                ('isbn', models.CharField(max_length=64)),
                ('format', models.CharField(max_length=30)),
                ('brief', models.TextField()),
                ('via', models.URLField()),
                ('pub_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
