# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books", "0002_book_tags")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "draft"), (1, "published")], default=0
            ),
        )
    ]
