# Generated by Django 3.2.9 on 2021-11-30 14:36

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0007_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exif",
            name="info",
            field=models.JSONField(encoder=json.encoder.JSONEncoder),
        ),
    ]
