# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='origin_link',
            field=models.URLField(max_length=255, null=True, unique=True, verbose_name='origin_link'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='tags'),
        ),
    ]
