# Generated by Django 2.2.9 on 2019-12-28 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("tutorials", "0002_tutorial_tags")]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutorial",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
