# Generated by Django 3.2.11 on 2022-02-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0003_auto_20191228_0910"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorial",
            old_name="created_datetime",
            new_name="created_at",
        ),
    ]
