# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20180530_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-published_at'], 'verbose_name': 'tutorial', 'verbose_name_plural': 'tutorial'},
        ),
    ]
